# Generated by Django 5.2.7 on 2025-10-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(blank=True, max_length=100, null=True)),
                ('book_author', models.CharField(blank=True, max_length=100, null=True)),
                ('book_category', models.CharField(blank=True, max_length=100, null=True)),
                ('book_price', models.IntegerField(blank=True, null=True)),
                ('book_publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('book_description', models.CharField(blank=True, max_length=100, null=True)),
                ('book_cover_image', models.ImageField(blank=True, null=True, upload_to='cover image')),
            ],
        ),
    ]
