# Generated by Django 5.2.7 on 2025-11-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registrationdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_password', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_conform_password', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
