# Generated by Django 5.2.7 on 2025-11-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_message', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
